name: Publish Docs
on:
  push:
    branches: [ main ]
    paths:
      - "docs/**"
      - "website/**"
      - "images/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '12'

      - uses: olafurpg/setup-scala@v13
      - uses: olafurpg/setup-gpg@v3

      - name: Publish docs to Github Pages 🚀
        run: sbt '++2.12.17 docs/docusaurusPublishGhpages'
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
