name: CI
on:
  push:
    branches: [ main ]

  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        os: [ 'ubuntu-latest', 'windows-latest' ]

    steps:
      - name: Checkout Course Management Tools Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: coursier/setup-action@v1
        with:
          jvm: graalvm-java17:22.3.1

      - name: Set up caching
        uses: coursier/cache-action@v6

      #- name: Run tests
      #  shell: bash
      #  run: sbt test

      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Native image generation
        shell: bash
        run: |
          cmake -G "NMake Makefiles" .
          nmake
          sbt nativeImage

  formatting:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout Course Management Tools Repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt-hotspot
          cache: 'sbt'

      - name: Check code formatting
        run: sbt "scalafmtCheckAll ; scalafmtSbtCheck"
